name: Scan Container Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  FALCON_CLIENT_SECRET: "${{ secrets.Client_Secret }}"
  FALCON_CLIENT_ID: "${{ secrets.Client_ID }}"
  FALCON_CLOUD_REGION: 'us-1'
  CONTAINER_REPO: 'container-upload.us-1.crowdstrike.com'
  CONTAINER_TAG: "${{ github.run_id }}"

jobs:

  build-scan:
    runs-on: ubuntu-latest
        
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        context: '.'
        push: false
        tags: "${{ env.CONTAINER_REPO }}:${{ env.CONTAINER_TAG }}"
    
    - name: Scan Container Image from Repository
      uses: CrowdStrike/container-image-scan-actionv0.4
      id: image-scan
      with:
         container_repository: "${{ env.CONTAINER_REPO }}"
         container_tag: "${{ env.CONTAINER_TAG }}"
         crowdstrike_region: "${{ env.FALCON_CLOUD_REGION }}"
#         crowdstrike_score: 500
         
    - name: Push docker image
      run: docker push "${{ env.CONTAINER_REPO }}:${{ env.CONTAINER_TAG }}"
          
    - name: Do something if high vulns found
      run: echo "VULNS FOUND - EXITCODE - ${{ steps.image-scan.outputs.exit-code }}"
      if:  always() && steps.image-scan.outputs.exit-code == 1
