    name: Push Container Images

    on:
     push:
      branches: [ main ]
     pull_request:
      branches: [ main ]
    
    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        username: "${{ secrets.DOCKER_USER }}"
        password: "${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push docker image to docker registry
      uses: docker/build-push-action@v2.4.0
      with:
        context: '.'
        push: false
        tags: "sanket3020/githubpush:${{ env.CONTAINER_TAG }}"
    
    - name: Push docker image
      run: docker push "sanket3020/githubpush:${{ env.CONTAINER_TAG }}"
