name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag container-upload.us-1.crowdstrike.com:$(date +%s)
    - name: Publish To Crowdstrike
      with:
       username: ${{ secrets.Client_ID }}
       password: ${{ secrets.Client_Secret }}
       registry: container-upload.us-1.crowdstrike.com
       tags: $(date +%s)
       run: docker push container-upload.us-1.crowdstrike.com:$(date +%s)
      
